name: tubes_pinwave
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  dio: 5.3.2
  intl: 0.18.1
  shared_preferences: 2.2.1
  lottie: 1.3.0
  basic_utils: 5.6.1
  loader_overlay: 2.1.0
  collection: 1.18.0
  shimmer: 2.0.0
  flutter_image_compress: 2.1.0
  image_picker: 1.0.6
  camera: 0.10.5+4
  package_info_plus: 4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lottie/
    - assets/logo.jpeg
